### ISSUE TITLE
README needs to be updated.

### ISSUE THREAD

**Issue by Rmcavin** [Rmcavin/Leaflet-Practice#3]
This program has no updated README file as of right now. It needs to be updated so users understand where to get data, how to prepare data, and how to use the program.

**Comment by hamer-iboshi** [comment]
I will work on it!

**Comment by Rmcavin** [comment]
Thanks! :)

**Comment by bdharris08** [comment]
Great job @hi15 !! Still amazed you found the data.

**Comment by hamer-iboshi** [comment]
Thank you! :)

**Comment by Rmcavin** [comment]
Thanks @hi15 you did an awesome job! :) Feel free to follow me and contribute in the future, I'm going to be working on quite a few things in the next few weeks.
